name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Retrieve version
        run: |
          echo "TAG_NAME=$(curl --silent 'https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224' | awk -vRS="</a>" '{ gsub(/.*<a +href=\042/,""); gsub(/\042.*/,""); print; }' | grep -e "^https://www.makemkv.com/download/makemkv-.*tar.gz$" | cut -d- -f3- | cut -d. -f1-3 | uniq | sort | tail -n1)" >> $GITHUB_OUTPUT
        id: version
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            clingclangclick/docker-ripper:${{ steps.version.outputs.TAG_NAME }}

